# nixpacks.toml

[phases.setup]
nixPkgs = ['...', 'pkgs.elixir_1_15']
aptPkgs = ['...', 'gcc', 'libtool']

[phases.build]
cmds = ['mix compile', 'mix ecto.setup', 'mix assets.deploy']

# [start]
# cmd = './bin/railway start'
